INSERT INTO ARTIST (ARTIST_NAME) VALUES ('The Beatles')
INSERT INTO ARTIST (ARTIST_NAME) VALUES ('Royal Hunt')
INSERT INTO ARTIST (ARTIST_NAME) VALUES ('AC/DC')

INSERT INTO ALBUM (ALBUM_TITLE, ALBUM_YEAR, ARTIST_ID) VALUES ('For Those About to Rock We Salute You', 1981, 3)
INSERT INTO ALBUM (ALBUM_TITLE, ALBUM_YEAR, ARTIST_ID) VALUES ('Paradox', 1997, 2)
INSERT INTO ALBUM (ALBUM_TITLE, ALBUM_YEAR, ARTIST_ID) VALUES ('Abbey Road', 1969, 1)
        
INSERT INTO SONG (DISC, SONG_TITLE, TRACK, ALBUM_ID) VALUES (1, 'Something', 2, 3)
INSERT INTO SONG (DISC, SONG_TITLE, TRACK, ALBUM_ID) VALUES (1, 'For Those About to Rock We Salute You', 1, 1)
INSERT INTO SONG (DISC, SONG_TITLE, TRACK, ALBUM_ID) VALUES (1, 'Come Together', 1, 3)
INSERT INTO SONG (DISC, SONG_TITLE, TRACK, ALBUM_ID) VALUES (1, 'River of Pain', 2, 2)
INSERT INTO SONG (DISC, SONG_TITLE, TRACK, ALBUM_ID) VALUES (1, 'The Awakening', 1, 2)
INSERT INTO SONG (DISC, SONG_TITLE, TRACK, ALBUM_ID) VALUES (1, 'I Put the Finger on You', 2, 1)